production:
  adapter: postgres
  encoding: unicode
  host: 'POSTGRES_ADDRESS'
  port: 5432
  database: carto_db_production
  username: postgres
  password: 'POSTGRES_PASS'
  conn_validator_timeout: 900

staging:
  adapter: postgres
  encoding: unicode
  host: 'POSTGRES_ADDRESS'
  port: 5432
  database: carto_db_staging
  username: postgres
  password: 'POSTGRES_PASS'
  conn_validator_timeout: 900

development:
  adapter: postgres
  encoding: unicode
  host: 'POSTGRES_ADDRESS'
  port: 5432
  database: carto_db_development
  username: postgres
  password: 'POSTGRES_PASS'
  conn_validator_timeout: 900
  pool: 50

test:
  adapter: postgres
  encoding: unicode
  database: carto_db_test
  host: 'POSTGRES_ADDRESS'
  port: 5432  
  username: postgres
  password: 'POSTGRES_PASS'
  conn_validator_timeout: -1

