defaults: &defaults
  session_domain:     ''
  subdomainless_urls: true
  account_host:       '127.0.0.1:3000'
  account_path:       '/account'
  vizjson_cache_domains: ['']
  tiler:
    internal:
      domain:        ''
      host:          '127.0.0.1'
    private:
      domain:        ''
    public:
      domain:        ''
  sql_api:
    private:
      domain:     ''
    public:
      domain:     ''
  developers_host:    'http://127.0.0.1:3000'
  org_metadata_api:
    host: '127.0.0.1'
  layer_opts:
    data:
      options:
        tiler_domain:       ""
        sql_domain:         ""
  app_assets:
    asset_host: "//127.0.0.1:3000"
  avatars:
    gravatar_enabled: true
    base_url: '//127.0.0.1:3000'
    kinds: ['stars', 'mountains']
    colors: ['red', 'blue']
